spring:
  datasource:
    url: "${{ secrets.DATABASE_ENDPOINT }}"
    username: "${{ secrets.DATABASE_USER_NAME }}"
    password: "${{ secrets.DATABASE_PASSWORD }}"
    driver-class-name: org.postgresql.Driver